import Head from "next/head";
import Toolbar from "../components/Toolbar";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>News App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Toolbar />
      <div className={styles.pageContainer}>
        <h1>NEXT.js News App</h1>
        <h3>One Stop For Every News Article</h3>
      </div>
    </div>
  );
}
